site_name: NH Switch Guide
copyright: Copyright &copy; 2023 <a href="https://discord.gg/C29hYvh" target="_blank">Nintendo Homebrew</a>, Maintained by the <a href="/switch-guide/about">NH Discord Server</a>.
site_description: Switch CFW Guide.
site_author: NH Discord Server.
site_url: https://guide.suchmeme.nl/
repo_url: https://github.com/nh-server/switch-guide
repo_name: NH Switch Guide

theme:
  name: material
  favicon: img/favicon.ico
  features:
    - toc.integrate
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - navigation.tracking

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/wrench

nav:
    - Home: index.md
    - User Guide:
        - 'Getting Started': 'user_guide/getting_started.md'
        - 'RCM': 'user_guide/rcm.md'  
        - 'Entering RCM': 'user_guide/emummc/entering_rcm.md'
        - 'Sending a payload': 'user_guide/emummc/sending_payload.md'      
        - 'Partitioning the SD': 'user_guide/emummc/partitioning_sd.md'    
        - 'SD preparations': 'user_guide/emummc/sd_preparation.md'
        - 'Making the emuMMC': 'user_guide/emummc/making_emummc.md'
        - 'Launching CFW': 'user_guide/emummc/launching_cfw.md'
    - Extras:
        - 'Blocking Nintendo servers': 'extras/blocking_nintendo.md'
        - 'Restoring a NAND Backup': 'extras/nandrestore.md'
        - 'AutoRCM': 'extras/autorcm.md'
        - 'Dumping Title Keys': 'extras/dumping_title_keys.md'
        - 'Theming': 'extras/theming.md'
        - 'Save Management': 'extras/save_management.md'
        - 'Game Modding': 'extras/game_modding.md'
        - 'Game Cheats': 'extras/cheats.md'
        - 'Linux injection without root': 'extras/adding_udev.md'
        - 'Showing File Name Extensions (Windows)': 'extras/showing_file_extensions.md'
        - 'Alternate Boot Setups': 'extras/alternate_bootsetups.md'
        - 'RCM Payload Injectors Information': 'extras/rcm_injectors.md'
        - 'Updating CFW': 'extras/updating.md'
        - 'Changing SD cards': 'extras/transfer_sd.md'
        - 'Glossary': 'extras/glossary.md'
    - FAQ: faq.md
    - About: about.md
    
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      toc_depth: 3

extra_css:
    - css/custom.css
